language: php

php:
  - "7.2"

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

dist: trusty

before_script:
  - composer self-update
  - composer install --no-interaction

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME_PRD=glowing-thunder-215513
    - CLUSTER_NAME_PRD=siwecoscluster
    - CLOUDSDK_COMPUTE_ZONE=europe-west1-b

jobs:
  include:
    - stage: "Testing"
      name: "PHPUnit Test"
      script: vendor/bin/phpunit
    - stage: "Building"
      name: "Docker Image"
      - script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t "$DOCKER_IMAGE" .
        - docker images
        - docker tag "$DOCKER_IMAGE" "$DOCKER_REPO"/"$DOCKER_IMAGE":"$TRAVIS_BRANCH"
        - docker push "$DOCKER_REPO"/"$DOCKER_IMAGE":"$TRAVIS_BRANCH"
      if: branch = master
      name: "Tag Docker Image as `latest`"
      - script:
        - docker tag "$DOCKER_IMAGE" "$DOCKER_REPO"/"$DOCKER_IMAGE":latest
        - docker push "$DOCKER_REPO"/"$DOCKER_IMAGE":latest
    - stage: "Deploying"
      name: "Preperations"
      - script:
        - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
        - source /home/travis/google-cloud-sdk/path.bash.inc
        - gcloud --quiet version
        - gcloud --quiet components update
        - gcloud --quiet components update kubectl
      if: branch = develop
      name: "Deploy staging"
      - script:
        - echo $GCLOUD_KEY | base64 --decode -i > ${HOME}/gcloud-service-key.json
        - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
        - gcloud --quiet config set project $PROJECT_NAME_PRD
        - gcloud --quiet config set container/cluster $CLUSTER_NAME_PRD
        - gcloud --quiet config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
        - gcloud --quiet container clusters get-credentials $CLUSTER_NAME_PRD
        - kubectl patch deployment siwecos-business-layer --namespace staging -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\", \"commit\":\"$TRAVIS_COMMIT\"}}}}}"
      if: branch = master
      name: "Deploy production"
      - script:
        - echo $GCLOUD_KEY | base64 --decode -i > ${HOME}/gcloud-service-key.json
        - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
        - gcloud --quiet config set project $PROJECT_NAME_PRD
        - gcloud --quiet config set container/cluster $CLUSTER_NAME_PRD
        - gcloud --quiet config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
        - gcloud --quiet container clusters get-credentials $CLUSTER_NAME_PRD
        - kubectl patch deployment siwecos-business-layer --namespace production -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\", \"commit\":\"$TRAVIS_COMMIT\"}}}}}"
