language: php

php:
  - "7.2"

services:
  - elasticsearch

cache:
  directories:
    - "./vendor"

dist: trusty

env:
  - ELASTICSEARCH_HOST=127.0.0.1

before_script:
  - sleep 10
  - composer selfupdate
  - composer install

script:
  - ./vendor/bin/phpunit
  - curl -L -o /tmp/translation-files.zip https://gitreleases.dev/gh/SIWECOS/translations/latest/translation-files.zip
  - unzip -o -d resources/lang /tmp/translation-files.zip
  - docker build -t siwecos-business-layer .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: develop
    script: >-
      docker tag siwecos-business-layer siwecos/siwecos-business-layer:develop &&
      docker push siwecos/siwecos-business-layer:develop
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script: >-
      docker tag siwecos-business-layer siwecos/siwecos-business-layer:latest &&
      docker push siwecos/siwecos-business-layer:latest
  - provider: script
    skip_cleanup: true
    on:
      tags: true
    script: >-
      docker tag siwecos-business-layer siwecos/siwecos-business-layer:$TRAVIS_TAG &&
      docker push siwecos/siwecos-business-layer:$TRAVIS_TAG
